type User = [string, string, number, string]

// durch das export können wir unsere daten wo anders nutzen
export const userArr: User[] = [
    ["Anton", "Müller", 30, "Berlin"],
    ["Sophia", "Schmidt", 25, "Bayern"],
    ["Maximilian", "Fischer", 40, "Hamburg"],
    ["Lena", "Weber", 28, "Baden-Württemberg"],
    ["Paul", "Schneider", 35, "Sachsen"],
    ["Emma", "Koch", 32, "Nordrhein-Westfalen"],
    ["Noah", "Richter", 22, "Rheinland-Pfalz"],
    ["Mia", "Wagner", 27, "Niedersachsen"],
    ["Ben", "Schulz", 45, "Hessen"],
    ["Lukas", "Krüger", 19, "Saarland"],
    ["Hannah", "Hoffmann", 31, "Schleswig-Holstein"],
    ["Finn", "Mayer", 33, "Thüringen"],
    ["Anna", "Becker", 24, "Mecklenburg-Vorpommern"],
    ["Elias", "Wolf", 36, "Brandenburg"],
    ["Marie", "Jung", 29, "Sachsen-Anhalt"],
    ["Leon", "Zimmermann", 38, "Bremen"],
    ["Luis", "Klein", 20, "Berlin"],
    ["Laura", "Neumann", 26, "Bayern"],
    ["Tim", "Braun", 34, "Hamburg"],
    ["Maya", "Schwarz", 23, "Baden-Württemberg"],
    ["Julian", "Zimmer", 41, "Sachsen"],
    ["Emily", "Hartmann", 21, "Nordrhein-Westfalen"],
    ["Liam", "Schmitt", 42, "Rheinland-Pfalz"],
    ["Johanna", "Krause", 30, "Niedersachsen"],
    ["Henry", "Lang", 18, "Hessen"],
    ["Lea", "Vogel", 39, "Saarland"],
    ["Luca", "Peters", 27, "Schleswig-Holstein"],
    ["Nina", "Fuchs", 25, "Thüringen"],
    ["Tom", "Scholz", 37, "Mecklenburg-Vorpommern"],
    ["Sarah", "Franke", 28, "Brandenburg"],
    ["Matteo", "Werner", 32, "Sachsen-Anhalt"],
    ["Sophie", "Lorenz", 24, "Bremen"],
    ["Jannik", "Weiß", 33, "Berlin"],
    ["Eva", "König", 22, "Bayern"],
    ["David", "Schubert", 29, "Hamburg"],
    ["Lina", "Meier", 40, "Baden-Württemberg"],
    ["Felix", "Winkler", 31, "Sachsen"],
    ["Marlene", "Günther", 26, "Nordrhein-Westfalen"],
    ["Philipp", "Hansen", 35, "Rheinland-Pfalz"],
    ["Clara", "Schilling", 23, "Niedersachsen"],
    ["Theo", "Horn", 21, "Hessen"],
    ["Elisa", "Busch", 38, "Saarland"],
    ["Jonas", "Schuster", 34, "Schleswig-Holstein"],
    ["Marie", "Kühn", 28, "Thüringen"],
    ["Anton", "Schäfer", 36, "Mecklenburg-Vorpommern"],
    ["Klara", "Brandt", 19, "Brandenburg"],
    ["Lara", "Engel", 25, "Sachsen-Anhalt"],
    ["Oskar", "Schwarz", 27, "Bremen"],
    ["Amelie", "Beck", 30, "Hessen"],
    ["Tobias", "Friedrich", 35, "Berlin"],
];